### ISSUE TITLE
unable to install prozess module

### ISSUE THREAD

**Issue by venkateshparuchuri8** [cainus/Prozess#56]
i am using kafka_2.11-0.10.2.0. the server is working properly.as a producer i am sending messages and as a consumer retrieving messages also.but for the ui integration i am using express frame work to connect kafka by using Proozess module.

**Comment by elee** [comment]
Aloha @venkateshparuchuri8 

This project is largely unmaintained and does not support recent versions of Kafka, namely 0.10.2.0 which you are using:

https://github.com/cainus/Prozess/blob/a0074eb9ee86d2cdf433b292031aec9a56aa8cac/README.md

View the compatibility matrix for more info. Sorry.
